### PR TITLE
Add support for Windows agents

### PR DESCRIPTION
**Pull request by spewu**
I had to add support for building on Windows since we have one repo with a legacy .NET Framework app. So, here are the changes required, in case you are interested.

### CODE REVIEW

**Comment by spewu** [comment]
@nmbro In case you are interested in adding support for running on Windows

**Comment by nmbro** [comment]
How did it work out for you?

I experienced that the Windows build depending on solution size had a tendency to kill the shared runner because it ran out of memory.

But for smaller solution it would work fine.

**Comment by spewu** [comment]
Oh, ok. I am using it on a solution with 86 projects, and I guess that it has several thousand lines of code. The build takes about 30 minutes on the standard Github Windows runner.

I have not experienced any problems so far 🤞

**Review by nmbro — APPROVED** [review]

**Comment by spewu** [comment]
@nmbro Nice, thanks for merging the PR. I have now switched to using the action from this repo instead of my fork, but I needed to use the commit SHA, as you didn't create a new release:

```
uses: visma-prodsec/coverity-on-polaris-workflow@4717770d3738b0ac126c665f7d5b719f192c3327
```

It works, but maybe you want to create a new release (and then also update the README, as that one links to `v1` currently, which won't work for the Windows version)

**Comment by nmbro** [comment]
oh, let me fix that!

**Comment by nmbro** [comment]
v2 has been released

**Pull request merged**
